### PR TITLE
fix for #268 - fix(http): proper creation of $_SERVER['REQUEST_URI']

### LINKED ISSUE #268: Symfony (http foundation) request->getRequestUri() doesn't contain query string
**Describe the bug**
The creation of Http Request in the `RequestFactory` doesn't set the `$_SERVER[REQUEST_URI]` parameter to the `$server` variable, which results in wrong value returned by calling `$request->getRequestUri()`. 

**Steps To Reproduce**
When a Symfony app with swoole bundle with gets requested with an url like this: `http://localhost:9501/twig?test=abc&wtf=123`, calling `$request->getRequestUri()` somewhere in the code, will return '/twig'.

**Expected behavior**
The method call should return this value: `/twig?test=abc&wtf=123`

Reference in symfony's Http/Request code: https://github.com/symfony/http-foundation/blob/1b66b861f3ff55fb39c13822a0fc915018b5ac84/Request.php#L1005

**Environment (please complete the following information):**
 - OS: Linux
 - PHP Version: 7.3.15
 - Swoole Version: 4.4.8
 - Symfony Version: 5.1.1
 - Running in docker: Yes

**Proposed fix**
The bug happens because this line: https://github.com/symfony/http-foundation/blob/v5.1.1/Request.php#L413 isn't called by creating the Request instance in the `RequestsFactory`

One solution would be to add these two lines into the factory:
```php
$queryString = $server['QUERY_STRING'] ?? '';
$server['REQUEST_URI'] = $server['REQUEST_URI'] . ($queryString !== '' ? '?' . $queryString : '');
```

Another solution would be to call Request::create(), instead of just calling the Request class constructor directly.

### PR DESCRIPTION
**Pull request by Rastusik**
It's more complicated to call the request factory method and these two lines would need to be written anyway

Fixes #269

### CODE REVIEW

File: src/Bridge/Symfony/HttpFoundation/RequestFactory.php [hunk 1]
```diff
@@ -21,6 +21,9 @@ public function make(SwooleRequest $request): HttpFoundationRequest
             $server['HTTP_'.\mb_strtoupper(\str_replace('-', '_', $key))] = $value;
         }
 
+        $queryString = $server['QUERY_STRING'] ?? '';
```
Comment (k911) [inline src/Bridge/Symfony/HttpFoundation/RequestFactory.php:24]: Are you certain that swoole sets `$server['QUERY_STRING']` ?

Comment (Rastusik) [reply src/Bridge/Symfony/HttpFoundation/RequestFactory.php:24]: yes, proof is here: https://github.com/swoole/swoole-src/blob/master/swoole_http_request.cc#L185

and here: https://github.com/swoole/swoole-src/blob/master/swoole_http_request.cc#L320

**Comment by k911** [comment]
I'll test it tommorow.

**Review by k911 — APPROVED** [review]
